src/objects/ApplicationLog__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApexMethod__c</fullName>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationArea__c</fullName>
        <label>Application Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Logs</relationshipLabel>
        <relationshipName>ApplicationLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogType__c</fullName>
        <label>Log Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <externalId>true</externalId>
        <label>Transaction ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Application Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppLog__e.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>ApexClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApexMethod__c</fullName>
        <label>ApexMethod</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApplicationArea__c</fullName>
        <label>ApplicationArea</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <label>ExceptionType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogType__c</fullName>
        <label>LogType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TransactionId__c</fullName>
        <label>TransactionId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AppLog</label>
    <pluralLabel>AppLogs</pluralLabel>
    <!--publishBehavior>PublishAfterCommit</publishBehavior-->
</CustomObject>

src/classes/AppLoggerHelper.cls
/**
 * Created by Tim.Peterson on 8/23/2019.
 */

public without sharing class AppLoggerHelper {

    public static void storeApplicationLogEntry(List<AppLog__e> logList){
        List<ApplicationLog__c> logsToInsert = new List<ApplicationLog__c>();
        for(AppLog__e log : logList)
        {
            ApplicationLog__c appLog = new ApplicationLog__c(
                    LogType__c = log.LogType__c
                    ,Message__c = log.Message__c
                    ,ApexClass__c = log.ApexClass__c
                    ,ApexMethod__c = log.ApexMethod__c
                    ,ApplicationArea__c = log.ApplicationArea__c
                    ,ExceptionType__c = log.ExceptionType__c
                    ,TransactionId__c = log.TransactionId__c
                    ,Contact__c = log.Contact__c
            );


            logsToInsert.add(appLog);
        }


        insert logsToInsert;
    }
}